sudo: false

language: php

php:
  - 7.1
  - 7.2

before_install:
  - composer self-update

install:
  - travis_retry composer install --no-interaction
  - composer info

script:
  - vendor/bin/phpcs
  - vendor/bin/phpunit
